ttttttttttt - kopia/BethanysPieShop/Models/Pie.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BethanysPieShop.Models
{
    public class Pie
    {
        public int PieId { get; set; }
        public string Name { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        public string AllergyInformation { get; set; }
        public decimal Price { get; set; }
        public string ImageUrl { get; set; }
        public string ImageThumbnailUrl { get; set; }
        public bool IsPieOfTheWeek { get; set; }
        public bool InStock { get; set; }
        public int CategoryId { get; set; }
        public Category Category { get; set; }
        public List<Commentary> CommentaryList { get; set; }
        public Pie ProductDetail { get; set; }

       
        public string GradeAverage { get; set; }
    }
   
}

ttttttttttt - kopia/BethanysPieShop/Controllers/CommentaryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BethanysPieShop.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using BethanysPieShop.ViewModels;


// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Bageriet.Controllers
{

    [Authorize]
    public class CommentaryController : Controller
    {
        private readonly ICommentary _CommentaryRepository;
        private Commentary _Commentary;

        public CommentaryController(ICommentary CommentaryRepository)
        {
            _CommentaryRepository = CommentaryRepository;
        }

       
        public IActionResult CommentaryD(int id)
        {
           
            return View();
        }

        [HttpPost]
        public IActionResult CommentaryD(Commentary newCommentary)
        {


            _Commentary = newCommentary;

            // Hvordan får jeg mit pieId med fra order formen?          

            if (_Commentary.CommentMessage == "")
            {
                ModelState.AddModelError("", "Please insert Your Review is empty");
            }

            if (ModelState.IsValid)
            {
                _CommentaryRepository.CreateCommentAndAddToDatabase(newCommentary);
                return RedirectToAction("ReviewComplete");
            }

            return View(newCommentary);
        }

        public IActionResult ReviewComplete()
        {
            ViewBag.ReviewCompleteMessage = "Thank you";
            return View();
        }
    }
}

ttttttttttt - kopia/BethanysPieShop/Controllers/PieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BethanysPieShop.Models;
using BethanysPieShop.ViewModels;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace BethanysPieShop.Controllers
{
    public class PieController : Controller
    {
        private readonly IPieRepository _pieRepository;
        private readonly ICategoryRepository _categoryRepository;

        public PieController(IPieRepository pieRepository, ICategoryRepository categoryRepository)
        {
            _pieRepository = pieRepository;
            _categoryRepository = categoryRepository;
        }

        // GET: /<controller>/
        //public IActionResult List()
        //{
        //    //ViewBag.CurrentCategory = "Cheese cakes";

        //    //return View(_pieRepository.AllPies);
        //    PiesListViewModel piesListViewModel = new PiesListViewModel();
        //    piesListViewModel.Pies = _pieRepository.AllPies;

        //    piesListViewModel.CurrentCategory = "Cheese cakes";
        //    return View(piesListViewModel);
        //}

        public ViewResult List(string category)
        {
            IEnumerable<Pie> pies;
            string currentCategory;

            if (string.IsNullOrEmpty(category))
            {
                pies = _pieRepository.AllPies.OrderBy(p => p.PieId);
                currentCategory = "All pies";
            }
            else
            {
                pies = _pieRepository.AllPies.Where(p => p.Category.CategoryName == category)
                    .OrderBy(p => p.PieId);
                currentCategory = _categoryRepository.AllCategories.FirstOrDefault(c => c.CategoryName == category)?.CategoryName;
            }

            return View(new PiesListViewModel
            {
                Pies = pies,
                CurrentCategory = currentCategory
            });
        }


        public IActionResult Details(int id)
        {
            var pie = _pieRepository.GetPieById(id);
            if (pie == null)
                return NotFound();

            return View(pie);
        }
    }
}

ttttttttttt - kopia/BethanysPieShop/Views/Pie/Details.cshtml
@model Pie
@using Microsoft.AspNetCore.Identity

<h2>@Model.Name</h2>

<div class="thumbnail">
    <img alt="@Model.Name" src="@Model.ImageUrl">
    <div class="caption-full">
        <h3 class="pull-right">@Model.Price</h3>
        <h3>
            <a href="#">@Model.Name</a>
        </h3>
        <h4>@Model.ShortDescription</h4>
        <p>@Model.LongDescription</p>
        <div class="addToCart">
            <p class="button">
                <a class="btn btn-primary" asp-controller="ShoppingCart" asp-action="AddToShoppingCart"
                   asp-route-pieId="@Model.PieId">Add to cart</a>
            </p>
        </div>
    </div>
</div>
<div class="pull-right">
    <!--
        framräknat betygsgenomsnitt visas
        ev kommentarer visas
    -->
    <h2>That's what our customers think</h2>
    <h3>Average rating: @Model.GradeAverage</h3>





    <!--
        inloggade användare kan lämna kommentar
    -->

    <form asp-action="CommentaryD" method="post" class="form-horizontal" role="form">
        <div asp-validation-summary="All" class="text-danger"></div>

        <h3>Reviews</h3>

        <!-- möjlighet att lämna egen kommentar                  -->
        <div class="form-group">
            <div class="col-md-5">
                <input name="Text" class="form-control" />
            </div>
        </div>

        <!-- submit av lämnad kommentar                               -->
        <div class="form-group">
            <div class="col-md-offset-2 col-md-5">

                <input type="submit" name="Text"
                       asp-controller="Commentary" asp-action="CommentaryD"
                       asp-route-id="@Model.ProductDetail"
                       asp-route-text="Text"
                       class="btn btn-primary" value="comments" />
            </div>
        </div>

        <!--  lämna betyg 1-5                              -->
        <div class="form-group">
            <div class="col-md-5">
                <input name="Grade" class="form-control" />
            </div>
        </div>

        <!-- betyg-siffra                               -->
        <div class="form-group">
            <div class="col-md-offset-2 col-md-5">

                <input type="submit" name="Grade"
                       asp-controller="Commentary" asp-action="CommentaryD"
                       asp-route-id="@Model.ProductDetail"
                       asp-route-text="Grade"
                       class="btn btn-primary" value="Add rating" />
            </div>
        </div>
    </form>
</div>
<div>
    <p>
        <a asp-controller="Commentary" asp-action="CommentaryD" asp-route-pieId="@Model.PieId">add your own review</a>
    </p>
</div>

ttttttttttt - kopia/BethanysPieShop/Views/Pie/List.cshtml
@model PiesListViewModel


<h1>Products</h1>

@foreach (var pie in Model.Pies)
{
    <partial name="_PieCard" model="pie" />
}